[project]
name = "project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "gdown>=5.2.0",
    "lap>=0.5.12",
    "ultralytics>=8.3.233",
    "pillow>=10.0.0",
    "tqdm>=4.66.0",
    "matplotlib>=3.7.0",
]
